default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: imdb
  host: 127.0.0.1

test:
  <<: *default
  database: imdb_test
  host: 127.0.0.1
  min_messages: WARNING

production:
  <<: *default
  database: imdbee
